services:
  - type: web
    name: pacha-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: postgresql://postgres:[ro0cLjVHqrIIvH34]@db.ypkiqljimobynpymfubv.supabase.co:5432/postgres
